const storageKey='bibliocollect-theme';
function applyTheme(theme){const root=document.documentElement;const dark=theme==='dark';if(dark){root.setAttribute('data-vdbs-theme','dark')}else{root.removeAttribute('data-vdbs-theme')}document.querySelectorAll('[data-theme-toggle]').forEach((button)=>{button.setAttribute('aria-pressed',dark?'true':'false');const label=button.querySelector('[data-theme-label]');if(label)label.textContent=dark?'Hell':'Dunkel';});}
let initialTheme='light';try{initialTheme=localStorage.getItem(storageKey)==='dark'?'dark':'light'}catch(_){}applyTheme(initialTheme);
document.addEventListener('click',(event)=>{const button=event.target.closest('[data-theme-toggle]');if(!button)return;const next=document.documentElement.hasAttribute('data-vdbs-theme')?'light':'dark';applyTheme(next);try{localStorage.setItem(storageKey,next)}catch(_){}});
document.addEventListener('change',(event)=>{const field=event.target.closest('[data-auto-submit]');if(!field||!field.form)return;if(typeof field.form.requestSubmit==='function'){field.form.requestSubmit()}else{field.form.submit()}});
document.addEventListener('click',(event)=>{if(event.target.closest('[data-print]')){window.print()}});
document.addEventListener('change',(event)=>{const all=event.target.closest('[data-select-all]');if(!all||!all.form)return;all.form.querySelectorAll('input[type="checkbox"][name="'+all.dataset.selectAll+'"]').forEach((box)=>{box.checked=all.checked});});
document.addEventListener('input',(event)=>{const input=event.target.closest('[data-offset]');if(input){document.documentElement.style.setProperty(input.dataset.offset,(parseFloat(input.value)||0)+'mm')}});
document.addEventListener('click',(event)=>{const el=event.target.closest('[data-confirm]');if(el&&!window.confirm(el.dataset.confirm)){event.preventDefault()}});
document.addEventListener('click',async(event)=>{const button=event.target.closest('[data-isbn-lookup]');if(!button)return;const form=button.closest('form');const isbn=form.querySelector('[name=isbn]');const status=form.querySelector('[data-isbn-status]');if(!isbn||!status)return;status.textContent='Suche läuft …';try{const response=await fetch(button.dataset.isbnLookup+'?isbn='+encodeURIComponent(isbn.value),{headers:{Accept:'application/json'}});const data=await response.json();status.textContent=data.message||'';if(data.found){const title=form.querySelector('[name=title]');const author=form.querySelector('[name=author]');if(title&&title.value==='')title.value=data.title||'';if(author&&author.value==='')author.value=data.author||''}}catch(_){status.textContent='Die Suche ist gerade nicht erreichbar. Du kannst die Angaben selbst eintragen.'}});
document.addEventListener('keydown',(event)=>{if(event.key==='Enter'&&event.target.matches&&event.target.matches('[data-isbn-field]')){event.preventDefault();const button=event.target.closest('form').querySelector('[data-isbn-lookup]');if(button)button.click()}});
document.addEventListener('click',(event)=>{document.querySelectorAll('[data-account-menu][open]').forEach((menu)=>{if(!menu.contains(event.target))menu.removeAttribute('open')})});
document.addEventListener('keydown',(event)=>{if(event.key!=='Escape')return;document.querySelectorAll('[data-account-menu][open]').forEach((menu)=>{menu.removeAttribute('open');const summary=menu.querySelector('summary');if(summary)summary.focus()})});
function fitNav(nav){const inner=nav.querySelector('.bc-nav__inner');const more=inner&&inner.querySelector('[data-nav-more]');if(!inner||!more)return;const links=[...inner.querySelectorAll('[data-nav-item]')];const items=[...more.querySelectorAll('[data-nav-more-item]')];nav.classList.add('bc-nav--fit');links.forEach((l)=>{l.hidden=false});items.forEach((i)=>{i.hidden=true});more.hidden=true;if(inner.scrollWidth<=inner.clientWidth+1)return;more.hidden=false;const gap=parseFloat(getComputedStyle(inner).columnGap)||0;const available=inner.clientWidth-more.offsetWidth-gap;const active=links.findIndex((l)=>l.hasAttribute('aria-current'));const keep=new Set();let used=0;if(active>=0){used+=links[active].offsetWidth+gap;keep.add(active)}let open=true;links.forEach((l,i)=>{if(i===active||!open)return;const width=l.offsetWidth+gap;if(used+width<=available){used+=width;keep.add(i)}else{open=false}});links.forEach((l,i)=>{if(!keep.has(i)){l.hidden=true;if(items[i])items[i].hidden=false}});const details=more.querySelector('details');if(details)details.removeAttribute('open')}
function fitAllNavs(){document.querySelectorAll('[data-nav]').forEach(fitNav)}
let navFrame=0;window.addEventListener('resize',()=>{cancelAnimationFrame(navFrame);navFrame=requestAnimationFrame(fitAllNavs)});
document.addEventListener('DOMContentLoaded',fitAllNavs);window.addEventListener('load',fitAllNavs);if(document.fonts&&document.fonts.ready){document.fonts.ready.then(fitAllNavs)}

