const storageKey='bibliocollect-theme';
function applyTheme(theme){const root=document.documentElement;const dark=theme==='dark';if(dark){root.setAttribute('data-vdbs-theme','dark')}else{root.removeAttribute('data-vdbs-theme')}document.querySelectorAll('[data-theme-toggle]').forEach((button)=>{button.setAttribute('aria-pressed',dark?'true':'false');const label=button.querySelector('[data-theme-label]');if(label)label.textContent=dark?'Hell':'Dunkel';});}
let initialTheme='light';try{initialTheme=localStorage.getItem(storageKey)==='dark'?'dark':'light'}catch(_){}applyTheme(initialTheme);
document.addEventListener('click',(event)=>{const button=event.target.closest('[data-theme-toggle]');if(!button)return;const next=document.documentElement.hasAttribute('data-vdbs-theme')?'light':'dark';applyTheme(next);try{localStorage.setItem(storageKey,next)}catch(_){}});
document.addEventListener('change',(event)=>{const field=event.target.closest('[data-auto-submit]');if(!field||!field.form)return;if(typeof field.form.requestSubmit==='function'){field.form.requestSubmit()}else{field.form.submit()}});
document.addEventListener('click',(event)=>{if(event.target.closest('[data-print]')){window.print()}});
document.addEventListener('change',(event)=>{const all=event.target.closest('[data-select-all]');if(!all||!all.form)return;all.form.querySelectorAll('input[type="checkbox"][name="'+all.dataset.selectAll+'"]').forEach((box)=>{box.checked=all.checked});});
document.addEventListener('input',(event)=>{const input=event.target.closest('[data-offset]');if(input){document.documentElement.style.setProperty(input.dataset.offset,(parseFloat(input.value)||0)+'mm')}});
document.addEventListener('click',(event)=>{const el=event.target.closest('[data-confirm]');if(el&&!window.confirm(el.dataset.confirm)){event.preventDefault()}});
