const storageKey='bibliocollect-theme';
function applyTheme(theme){const root=document.documentElement;const dark=theme==='dark';if(dark){root.setAttribute('data-vdbs-theme','dark')}else{root.removeAttribute('data-vdbs-theme')}document.querySelectorAll('[data-theme-toggle]').forEach((button)=>{button.setAttribute('aria-pressed',dark?'true':'false');const label=button.querySelector('[data-theme-label]');if(label)label.textContent=dark?'Hell':'Dunkel';});}
let initialTheme='light';try{initialTheme=localStorage.getItem(storageKey)==='dark'?'dark':'light'}catch(_){}applyTheme(initialTheme);
document.addEventListener('click',(event)=>{const button=event.target.closest('[data-theme-toggle]');if(!button)return;const next=document.documentElement.hasAttribute('data-vdbs-theme')?'light':'dark';applyTheme(next);try{localStorage.setItem(storageKey,next)}catch(_){}});
document.addEventListener('change',(event)=>{const field=event.target.closest('[data-auto-submit]');if(!field||!field.form)return;if(typeof field.form.requestSubmit==='function'){field.form.requestSubmit()}else{field.form.submit()}});
document.addEventListener('click',(event)=>{if(event.target.closest('[data-print]')){window.print()}});
document.addEventListener('change',(event)=>{const all=event.target.closest('[data-select-all]');if(!all||!all.form)return;all.form.querySelectorAll('input[type="checkbox"][name="'+all.dataset.selectAll+'"]').forEach((box)=>{box.checked=all.checked});});
document.addEventListener('input',(event)=>{const input=event.target.closest('[data-offset]');if(input){document.documentElement.style.setProperty(input.dataset.offset,(parseFloat(input.value)||0)+'mm')}});
document.addEventListener('click',(event)=>{const el=event.target.closest('[data-confirm]');if(!el)return;if(el.dataset.confirmed==='1'){delete el.dataset.confirmed;return}event.preventDefault();if(typeof HTMLDialogElement==='undefined'){if(window.confirm(el.dataset.confirm)){el.dataset.confirmed='1';el.click()}return}const dialog=document.createElement('dialog');dialog.className='bc-confirm';dialog.setAttribute('aria-labelledby','bc-confirm-text');const text=document.createElement('p');text.id='bc-confirm-text';text.className='bc-confirm__text';text.textContent=el.dataset.confirm;const actions=document.createElement('div');actions.className='bc-confirm__actions';const cancel=document.createElement('button');cancel.type='button';cancel.className='bc-button bc-button--secondary';cancel.textContent='Abbrechen';const ok=document.createElement('button');ok.type='button';ok.className='bc-button bc-button--primary';ok.textContent=el.dataset.confirmLabel||'Bestätigen';actions.append(cancel,ok);dialog.append(text,actions);document.body.append(dialog);const close=()=>{dialog.close();dialog.remove();el.focus()};cancel.addEventListener('click',close);dialog.addEventListener('cancel',(e)=>{e.preventDefault();close()});ok.addEventListener('click',()=>{dialog.close();dialog.remove();el.dataset.confirmed='1';el.click()});dialog.showModal();cancel.focus()});
document.addEventListener('click',async(event)=>{const button=event.target.closest('[data-isbn-lookup]');if(!button)return;const form=button.closest('form');const isbn=form.querySelector('[name=isbn]');const status=form.querySelector('[data-isbn-status]');if(!isbn||!status)return;status.textContent='Suche läuft …';try{const response=await fetch(button.dataset.isbnLookup+'?isbn='+encodeURIComponent(isbn.value),{headers:{Accept:'application/json'}});const data=await response.json();status.textContent=data.message||'';if(data.found){const title=form.querySelector('[name=title]');const author=form.querySelector('[name=author]');if(title&&title.value==='')title.value=data.title||'';if(author&&author.value==='')author.value=data.author||''}}catch(_){status.textContent='Die Suche ist gerade nicht erreichbar. Du kannst die Angaben selbst eintragen.'}});
document.addEventListener('keydown',(event)=>{if(event.key==='Enter'&&event.target.matches&&event.target.matches('[data-isbn-field]')){event.preventDefault();const button=event.target.closest('form').querySelector('[data-isbn-lookup]');if(button)button.click()}});
document.addEventListener('click',(event)=>{const button=event.target.closest('[data-acc-toggle]');if(!button)return;const open=button.dataset.accToggle==='open';document.querySelectorAll('details[data-acc]').forEach((details)=>{details.open=open})});
document.addEventListener('click',(event)=>{document.querySelectorAll('[data-account-menu][open]').forEach((menu)=>{if(!menu.contains(event.target))menu.removeAttribute('open')})});
document.addEventListener('keydown',(event)=>{if(event.key!=='Escape')return;document.querySelectorAll('[data-account-menu][open]').forEach((menu)=>{menu.removeAttribute('open');const summary=menu.querySelector('summary');if(summary)summary.focus()})});
function fitNav(nav){const inner=nav.querySelector('.bc-nav__inner');const more=inner&&inner.querySelector('[data-nav-more]');if(!inner||!more)return;const links=[...inner.querySelectorAll('[data-nav-item]')];const items=[...more.querySelectorAll('[data-nav-more-item]')];nav.classList.add('bc-nav--fit');links.forEach((l)=>{l.hidden=false});items.forEach((i)=>{i.hidden=true});more.hidden=true;if(inner.scrollWidth<=inner.clientWidth+1)return;more.hidden=false;const gap=parseFloat(getComputedStyle(inner).columnGap)||0;const available=inner.clientWidth-more.offsetWidth-gap;const active=links.findIndex((l)=>l.hasAttribute('aria-current'));const keep=new Set();let used=0;if(active>=0){used+=links[active].offsetWidth+gap;keep.add(active)}let open=true;links.forEach((l,i)=>{if(i===active||!open)return;const width=l.offsetWidth+gap;if(used+width<=available){used+=width;keep.add(i)}else{open=false}});links.forEach((l,i)=>{if(!keep.has(i)){l.hidden=true;if(items[i])items[i].hidden=false}});const details=more.querySelector('details');if(details)details.removeAttribute('open')}
function fitAllNavs(){document.querySelectorAll('[data-nav]').forEach(fitNav)}
let navFrame=0;window.addEventListener('resize',()=>{cancelAnimationFrame(navFrame);navFrame=requestAnimationFrame(fitAllNavs)});
document.addEventListener('DOMContentLoaded',fitAllNavs);window.addEventListener('load',fitAllNavs);if(document.fonts&&document.fonts.ready){document.fonts.ready.then(fitAllNavs)}
// Kamera-Scan: Felder mit data-camera-scan bekommen einen Button „Kamera“ (nur mit Kamera und https). Der Wert „absenden“ schickt das Formular nach dem Treffer ab.
(function(){
const supported=()=>window.isSecureContext&&navigator.mediaDevices&&typeof navigator.mediaDevices.getUserMedia==='function';
let dialog=null,stopScan=null;
function build(){const d=document.createElement('dialog');d.className='bc-camera';d.setAttribute('aria-labelledby','bc-camera-title');d.innerHTML='<h2 id="bc-camera-title" class="bc-camera__title">Code mit der Kamera scannen</h2><video class="bc-camera__video" muted playsinline></video><p class="bc-camera__status" role="status"></p><div class="bc-camera__actions"><button type="button" class="bc-button bc-button--secondary" data-camera-cancel>Abbrechen</button></div>';d.addEventListener('close',()=>{if(stopScan){stopScan();stopScan=null}});d.querySelector('[data-camera-cancel]').addEventListener('click',()=>d.close());document.body.appendChild(d);return d}
function message(error){const name=error&&error.name;if(name==='NotAllowedError'||name==='SecurityError')return 'Der Zugriff auf die Kamera ist nicht erlaubt. Bitte im Browser erlauben oder die Nummer eintippen.';if(name==='NotFoundError'||name==='OverconstrainedError')return 'Es wurde keine Kamera gefunden. Bitte die Nummer eintippen.';if(name==='NotReadableError')return 'Die Kamera wird gerade von einer anderen App verwendet.';return 'Die Kamera konnte nicht gestartet werden. Bitte die Nummer eintippen.'}
async function open(input){if(!dialog)dialog=build();const video=dialog.querySelector('video');const status=dialog.querySelector('.bc-camera__status');status.textContent='Kamera wird gestartet …';if(!dialog.open)dialog.showModal();try{const {startScanner}=await import('./scanner.js');const stop=await startScanner(video,(code)=>{stopScan=null;input.value=code;input.dispatchEvent(new Event('input',{bubbles:true}));if(navigator.vibrate)navigator.vibrate(60);dialog.close();if(input.dataset.cameraScan==='absenden'&&input.form){if(typeof input.form.requestSubmit==='function'){input.form.requestSubmit()}else{input.form.submit()}}else{input.focus()}});if(!dialog.open){stop();return}stopScan=stop;status.textContent='Den Code vor die Kamera halten.'}catch(error){status.textContent=message(error)}}
function setup(){if(!supported())return;document.querySelectorAll('input[data-camera-scan]').forEach((input)=>{if(input.dataset.cameraReady)return;input.dataset.cameraReady='1';const button=document.createElement('button');button.type='button';button.className='bc-button bc-button--secondary bc-camera-button';button.textContent='Kamera';button.setAttribute('aria-label','Mit der Kamera scannen: '+((input.labels&&input.labels[0]&&input.labels[0].textContent)||'Code').trim());button.addEventListener('click',()=>open(input));const field=input.closest('.bc-field')||input;field.insertAdjacentElement('afterend',button)})}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&dialog&&dialog.open)dialog.close()});
document.addEventListener('DOMContentLoaded',setup);
})();
